### ISSUE TITLE
New error occurring with latest...

### ISSUE THREAD

**Issue by wgorman** [a5huynh/oauth2_proxy#6]
I get the following error with the latest build:

oauthproxy.go:527: error redeeming code Post https://github.com/login/oauth/access_token: x509: failed to load system roots and no roots provided

I quick search recommends this:

http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/

Thanks!

**Comment by a5huynh** [comment]
Nice catch @wgorman, just pushed out a new build with the fix!

**Comment by wgorman** [comment]
Thanks!
