### ISSUE TITLE
Tag current master please

### ISSUE THREAD

**Issue by brosander** [a5huynh/oauth2_proxy#8]
This project has been really useful for us but we need a specific version number to depend on.

Current master has a much smaller footprint and updated CA certificates.  In order to avoid depending on latest (and keep control over new image versions introduced into our system), we've forked and tagged the current [master branch as 2.2.1](https://github.com/corvana/oauth2_proxy/tree/2.2.1) and [set up a Dockerhub automated build for it](https://hub.docker.com/r/corvana/oauth2_proxy/tags/).

It might be a good idea to do a minor release tag and docker hub build for any significant improvements or bugfixes.

**Comment by a5huynh** [comment]
Hey @brosander! Thanks for reaching out. I was a little hesitant at first to tag the change in case any major issues came up (such as the missing CA certificates for instance), but your idea of a point release alleviates that concern. Just push out the new tag.

**Comment by brosander** [comment]
@a5huynh awesome! thanks for the quick turnaround! :+1:
