### ISSUE TITLE
Tag 2.2.1 does not reflect oauth2_proxy version

### ISSUE THREAD

**Issue by lubo** [a5huynh/oauth2_proxy#9]
Image tags should reflect version of application installed inside the image. Therefore, image `2.2.1` should have been tagged as `2.2`. Having image version `2.2.1` of oauth2_proxy version `2.2` is just confusing.

**Comment by a5huynh** [comment]
@lubo This was due to an update to the Docker image itself, see #5 & #7, and #8 for a short discussion of this change. 

Obviously, a bit problematic since we no longer directly track the bitly version but it was a quick compromise to get that change out for folks especially since v2.2.0 is almost a year old.

**Comment by lubo** [comment]
@a5huynh Thank you for the response. I understand what led you to this solution, but I don't think this is right nor sustainable. If you look around, many of the official Docker images suffer from similar issues. For example, [golang](https://hub.docker.com/_/golang/) image version `1.8` was originally based on Debian Jessie, but many users requested the image to be migrated to Debian Stretch. Since this could break backward compatibility, they've left `1.8` on Jessie and introduced a new tag, `1.8-stretch`, to solve the issue. I think the same solution is applicable here too. Tagging the new image as `2.2-debian` or similar instead would solve all the problems (at least from my point of view). Please, let me know what you think about this proposal.

**Comment by a5huynh** [comment]
@lubo Thanks for the concern, I agree that it isn't sustainable, just offering an explanation of how that tag came to be. 

Using tags such as `2.2-debian` can be something we do for future releases. Currently, I'd rather not break anyone's build that may be using the existing tag.

**Comment by lubo** [comment]
Why not adding a new tag now? It wouldn't break anything and at the same time, you don't have to remove the existing tag. I'd love to migrate to the Debian version of this image ASAP, but I cannot do that since the tag is misleading and there's a risk of the applicaton version changing silently.

**Comment by a5huynh** [comment]
@lubo Ah sorry, if thats all you needed, you should've lead with that! That's not a problem, `2.2-debian` has been pushed.
